######################################################################
# Automatically generated by qmake (2.01a) Tue Apr 5 14:10:08 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . src
INCLUDEPATH += . src

# Input
HEADERS += src/def.h src/gpvis.h src/node.h src/tree.h
SOURCES += src/def.cpp \
           src/gpvis.cpp \
           src/main.cpp \
           src/node.cpp \
           src/tree.cpp \
