######################################################################
# Automatically generated by qmake (2.01a) Thu Apr 7 16:03:21 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . src tinygp/src
INCLUDEPATH += . src
QT += testlib

# Input
HEADERS += src/def.h src/gpvis.h src/node.h src/tree.h
SOURCES += src/def.cpp \
           src/gpvis.cpp \
           src/main.cpp \
           src/node.cpp \
           src/tree.cpp \
